### ISSUE TITLE
setup-project-management

### ISSUE THREAD

**Issue by ejelome** [ejelome/mern-publisher#1]
### 1. Repo

- [x] as **Public**
- [x] with **README** file
- [x] with **.gitignore** file _(`Node`)_
- [x] with **LICENSE** file _(`MIT`)_

---

### 2. Settings

- [x] Enable **Automatically delete head branches**

   `/settings#merge_types_delete_branch`

- [x] **Add** Branch protection **rule**s _(`main`)_

   `/settings/branch_protection_rules/new`

   - [x] Enable **Require status checks to pass before merging**

      `/settings/branch_protection_rules/<id>#has_required_statuses`

      - [x] Enable **Require branches to be up to date before merging**

         `/settings/branch_protection_rules/<id>#strict_required_status_checks_policy`

   - [x] Enable **Include administrators**

      `/settings/branch_protection_rules/<id>#enforce_all_for_admins`

- [x] Add Notifications **Address**

   `/settings/notifications`

---

### 3. Wiki

- [x] **Create the first page**

   `/wiki/_new`

---

### 4. Projects

- [x] **Create a project**

   `/projects/new`

   - [x] **Project board name** as `Sprint 1: MVP`
   - [x] **Description** as `Create an MVP for core <repo> features.`
   - [x] **Project template** as `Automated Kanban`

---

### 5. Scrumban

- [x] Cleanup default notes

- [x] **Backlog (∞)**

   - [x] **Preset** as `None`

- [x] **Ready (2)**

   - [x] **Preset** as `To do`
   - [x] **Move issues here when...** as `Newly added`, `Reopened`

- [x] **WIP (1)**

   - [x] **Preset** as `In progress`
   - [x] **Move pull requests here when…** as `Newly added`, `Reopened`

- [x] **Done (∞)**

   - [x]  **Preset** as `Done`
   - [x] **Move issues here when…** as `Closed`
   - [x] **Move pull requests here when…** as `Merged`, `Closed with unmerged commits`

---

### 6. Milestone

- [x] **Create a milestone**

   `/milestones/new`

   - [x] **Title** as `<repo> with core functionalities`
   - [x] **Due date (optional)** as `yyy-mm-dd` _(e.g. 2 weeks)_
   - [x] **Description** as `Develop <description>.`
